### ISSUE TITLE
How to open a node when you hover the other node?

### ISSUE THREAD

**Issue by lkdnvc** [angular-ui-tree/angular-ui-tree#210]
Hello, please help.
 The essence of the problem is this:
  When I start to drag the item in the list, when you hover this item to a closed unit, it should open. How can I implement it?
 I would have been enough for it to know over what node I'm in the moment.
 I would be grateful for any help.

**Comment by krloscosta34** [comment]
This implementation is lost!!!
I think it happened in the commit 800dd0a43ce105d6301cd42038c1a28dbe3cd21e (Revert 5b1c360..ce185be) on 6 Feb 2015.

@clementprevot can you commit again?

**Comment by ConnectedReasoning** [comment]
Do you know way the rollback occurred? I'd like to see this feature become reinstated again.

**Comment by krloscosta34** [comment]
Maybe you can see what @clementprevot change and recommit it again.

**Comment by derek-adair** [comment]
Considering the health of htis project (no commits in 5 months)...

I'd suggest forking, manually adding this commit in and trying it out yourself.  If it works, write some tests and make a pull request.

Currently there is an issue open for helping this project along.  You're greatly encouraged to contribute anything and everything you can.

Cheers!

**Comment by krloscosta34** [comment]
@rribou , did you solve this problem?

**Comment by krloscosta34** [comment]
@StefanCodes, can you commit this modifications in the master project?

**Comment by StefanCodes** [comment]
@krloscosta34 Yep, I can do this.

@rribou, would you like to submit your changes to the project as a PR?

**Comment by rribou** [comment]
@StefanCodes done.

**Comment by StefanCodes** [comment]
Thank you @rribou!

I'm merged this locally and it looks good, but I'm concerned about the amount of support requests we might end up with. I'd like to include some documentation and a new example for the demo site.

If anybody has some spare cycles to update documentation and create an example that would be great (please add to https://github.com/angular-ui-tree/angular-ui-tree/pull/783). Otherwise, I plan to get to that this week and can roll out a new release.

**Comment by StefanCodes** [comment]
I added a basic example and updated the readme.

I feel like the basic behaviour is a bit annoying due to how aggressively the placeholder jumps around. This can be dealt with by anyone implementing this in a project, but it would be nice to make it a little cleaner out of the box. I'm considering that out of scope for holding up this release, though - this has dragged on long enough.

If anyone is having critical issues with this feature please let me know. If you have any suggestions or tweaks, open a new issue.

**Comment by ConnectedReasoning** [comment]
I tested this out. It works well. Thanks!

**Comment by krloscosta34** [comment]
Very good this implementation :)
Congratulation!!!!

But I have two suggestion:

when open a node on hover, call toggle callback (for example, I have lazy loading to children)
put a delay to open with hover, so the user can choose a node to open (and no every node)

**Comment by ltoshev** [comment]
Part of this code is missing in master now? Why?
