### ISSUE TITLE
 Recursive more than 10 knots, an error occurs

### ISSUE THREAD

**Issue by dftpnd** [angular-ui-tree/angular-ui-tree#218]
Recursive more than 10 knots, an error occurs:
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
screenshot link: http://pixs.ru/showimage/Snimokekra_9604130_13574121.png

**Comment by forcewill** [comment]
I know this issue is closed but using ng-repeat with ng-include
seem to be the wrong approach performance wise, it kicked me until i read this 
http://www.bennadel.com/blog/2738-using-ngrepeat-with-nginclude-hurts-performance-in-angularjs.htm
and then i solved the issue by using a recursive directive for my node template

using https://github.com/marklagendijk/angular-recursion

my html is 

     <div ui-tree="options" data-drag-enabled="treeOptions.dragEnabled" callbacks="options"
             data-drag-delay="100"
             data-empty-placeholder-enabled="false"
             id="tree-root">
            <ol ui-tree-nodes ng-model="treedata">
                <li ng-repeat="node in treedata track by $index" ui-tree-node

                    collapsed="true" ng-if="!collapsed">
                    <node></node>
                </li>
            </ol>
        </div>

and my directive is the following
    
    (function () {
        angular.module( "app" ).directive(
        "node",
        ['RecursionHelper', function(RecursionHelper) {

            return({
              
                compile: function(element) {
                    // Use the compile function from the RecursionHelper,
                    // And return the linking function(s) which it returns
                    return RecursionHelper.compile(element);
                },
                restrict: "E",
                templateUrl: "node.html"
            });
        }]
    );
    })();

where node.html is the following

    <div>
          ..NODE TEMPLATE HERE...

    <ol ui-tree-nodes="" ng-model="node.nodes" ng-show="!collapsed" style="outline: none;">
        <li ng-repeat="node in node.nodes track by $index" ui-tree-node>
            <node></node>
        </li>
    </ol>
    </div>

**Comment by trashhalo** [comment]
incase anyone else hits this this seems to work fine with components on more mordern angular. updated the failing plunkr to work. http://plnkr.co/edit/bzCki5rLI2mrmVmCs6OK?p=preview
