### ISSUE TITLE
beforeDrop with 'confirm' call in it causes '$apply already in progress'

### ISSUE THREAD

**Issue by bronielsen** [angular-ui-tree/angular-ui-tree#262]
Hi,

Love this plugin. Saved me a lot of time!

I am having a problem similar to the one discussed here: https://github.com/JimLiu/angular-ui-tree/issues/213

I am using Chrome. 

I created a beforeDrop callback in order to be able to allow the user to cancel the drop. 

For testing I currently have the following in the beforeDrop (in typescript):
<pre>
var confirmation: boolean;
confirmation = confirm(this.stringAreYouSure);
event.source.nodeScope.$$apply = false; // Note: I set this false for this test
</pre>

Since the $$apply is set to false, the drop never goes through.

With this I get an '$apply already in progress' error. If I remove the 'confirm' call like this:
<pre>
var confirmation: boolean;
// confirmation = confirm(this.stringAreYouSure);
event.source.nodeScope.$$apply = false; // Note: I set this false for this test
</pre>
I do not get the problem.

So the problem seems to be an interaction between the confirm call and the Angular UI Tree library.

Any ideas?

**Comment by inviolablegenesis** [comment]
@bronielsen: hi! i'm new to angular and to typescript. if you could help me, how did you get your callbacks called? the scope i'm using is `$scope: ITreeScope`.

ITreeScope is my custom interface and the content is only
```typescript
data: any[];
```

this has been my problem for days already since i'm not sure on what to use there for the callbacks to be called. 
if you could help me, i would really appreciate it! 

thank you.

**Comment by bronielsen** [comment]
Hi, did not notice this question before now. Did you find a solution for this?

**Comment by inviolablegenesis** [comment]
hi, yeah. the callbacks are now called.
