### ISSUE TITLE
How can I collapse all nodes when tree init?

### ISSUE THREAD

**Issue by hstarorg** [angular-ui-tree/angular-ui-tree#292]

**Comment by nobalmohan** [comment]
Set collapsed="true" in your ui-tree-node DOM

   <div ui-tree data-drag-enabled="false"  >
      <ol ui-tree-nodes ng-model="list" >
         <li ng-repeat="node in list" ui-tree-node   collapsed="true" ng-include="'nodes_render.html'"></li>
      </ol>
   </div>

**Comment by StefanCodes** [comment]
I found another workaround that works better for my scenario:

I added a new property onto my ui-tree-node object to encapsulate the collapsed value (that the tree resets during drag events) and defaulted it to true (since I want my fields collapsed on load).

My tree node:
    `<li ng-repeat="thing in things" ui-tree-node collapsed="thing.collapsed">`
        `<div ui-tree-handle>`
                `<a ng-click="toggle(this); field.collapsed = collapsed"></a>`
            `</div>`
    `</li>`


This is a small addition to simply adding collapsed="true" to the ui-tree-node that prevents the node from re-collapsing each time you drag and drop it. I'm having success expanding multiple nodes, and dragging and dropping them without their expanded state changing.

**Comment by ChavXO** [comment]
Can someone provide a toy example for how to do this? I can't seem to get it to work.

**Comment by dach89** [comment]
Im gonna leave this snippet here
If someone still have trouble getting this to work.

```HTML
<div ui-tree="treeOptions" id="tree-root" data-nodrag="true" callbacks="treeOptions" >
        <ol ui-tree-nodes="" data-nodrag="false" ng-model="lstObj">
                <li ng-repeat="obj in lstObj"  collapsed="true;" data-collapsed="true" ui-tree-node ng-include="'templet.html'"></li>
         </ol>
 </div>
```

**Comment by Quethzel** [comment]
you can use this code after load the treeview.
`$("#orgTree").data("kendoTreeView").collapse(".k-item");`
