### ISSUE TITLE
Future of angular-ui-tree?

### ISSUE THREAD

**Issue by honkskillet** [angular-ui-tree/angular-ui-tree#319]
@JimLiu  First, I would like to say thank you for all the hard work you have done on this project so far.  I know maintaining a repository like this is a time consuming, thankless job.

However, I believe that many users of this repo are in need of an update as to it's status.  Will it continue to be under active development?  If not, that is OK, but we need to know so we can make decisions on whether to use this repo, fork this repo or use an alternative.  Again, no one will hold it against you if you have to state that you do not have time actively develop this repo anymore, but we would really like to know.

Thank you in advance,
Alex

**Comment by JimLiu** [comment]
Sorry for long time no update with this component. 
One reason is I was really busy on work and family, another reason is that it's hard to upgrade after merged a lot of pulls.

Anyway, I begun to upgrades it again with other contributors. Already committed some code on branch [angular-ui-tree2](https://github.com/JimLiu/angular-ui-tree/tree/angular-ui-tree2).

What we are going to do:
1. Fix bugs
2. Reorganize the code, separate features into directives (like keyborad supports)
3. Improve the drag and drop
  - drag & copy nodes
  - drag & drop between multiple trees 
  - drag multiple nodes
4. easy to build a tree
  a) use <ui-tree> node to create a tree
  b) bind with tree data 
5. TBD

**Comment by honkskillet** [comment]
Awesome.  That's great news.

**Comment by chino23** [comment]
glad to have you back! :)

**Comment by ernestopye** [comment]
Great to hear! Love the work you've done with this component. Really appreciate it.

**Comment by boneskull** [comment]
:+1:

**Comment by Rodeoclash** [comment]
:+1:

**Comment by Voles** [comment]
I am figuring out how to improve the development + release flow.
Next weekend I'll create a proposal on a separate branch.

The idea is to:
-  improve the documentation generation flow using [Dgeni](https://github.com/angular/dgeni)
- add a task to deploy a new version of the website (containing latest examples + docs + API reference)
- use Gulp instead of Grunt

This is because I would like to have all documentation in one place, automate as much tests as possible and cleanup legacy stuff (issues, examples...)

**Comment by honkskillet** [comment]
@Voles  I look forward to your proposal.

**Comment by Voles** [comment]
@honkskillet part 1: #341 :-)

**Comment by honkskillet** [comment]
Any news on 2.1.6?

**Comment by chino23** [comment]
+1

**Comment by sheymann** [comment]
+1

**Comment by samuv** [comment]
+1

**Comment by povsim** [comment]
+1

**Comment by honkskillet** [comment]
Awesome to see recent activity in this repo.

**Comment by icfantv** [comment]
So, it's been nearly 7 months since this issue was created and not much has happened.  The angular-ui-tree2 branch indicated above is either not public or non-existent.

It seems like gobs of people want to use this library but it's starting to feel like the devs are not able to give it the attention it needs.  I'd rather be told it's dead rather than be strung along for months at a time.

Any update?
