### ISSUE TITLE
v2.4.0: Width of placeholder element?

### ISSUE THREAD

**Issue by muzigao** [angular-ui-tree/angular-ui-tree#454]
Hi,

Is there any way to adjust the width of placeholder element dynamically?

I realized that on the demo site (v2.1.5?), the placeholder is always taking the width of its content like this:
placeElm.css('width', $uiTreeHelper.width(scope.$element) + 'px');

Do i have to rollback to older version for this effect?

Thanks!

**Comment by BlakeBrown** [comment]
I'm looking for a fix to this as well, is there any way to provide a custom width in the newer version(s)?

**Comment by Voles** [comment]
@BlakeBrown does the fix work for you? Fixed in [v2.7.0](https://github.com/angular-ui-tree/angular-ui-tree/releases/tag/v2.7.0).

**Comment by BlakeBrown** [comment]
@Voles 

Actually that's the version that breaks it for me, I'm looking to style the placeholder width with CSS and as @muzigao wrote, the line that was introduced: placeElm.css('width', $uiTreeHelper.width(scope.$element) + 'px'); in angular-ui-tree.js forces the placeholder to always take the same width as the content being dragged. In my case, I'm looking to make the placeholder take 100% of the width available rather than being only as large as the content.

I'm thinking of either removing this line (I don't see why it's necessary? I think in most cases users would be okay styling the placeholder with CSS) or providing an option to disable/enable it. 

What are your thoughts?

**Comment by Voles** [comment]
@BlakeBrown the placeholder does neet the height to be set, because it has no content and would otherwise have a height of `0px`. However, for the `width`, the placeholder will take the full width available if it's a block-element. Because the placeholder element get's the `angular-ui-tree-placeholder` class, it is easy to style using CSS.

The PR which added the 'fix' (#470) doesn't really have an argument on why the width should be set explicitly. There's only a reference to a PR where it has been removed, also without any arguments.

I suggest we remove setting the `width` for the placeholder using JS. @BlakeBrown are you able to create a PR for this?

/cc @angular-ui-tree/developers

**Comment by BlakeBrown** [comment]
@Voles 

Yup of course! See #642 

Thanks for getting to me so quickly and with such a high-quality response. That was awesome! :D

**Comment by Voles** [comment]
Resolved by merging #642
