### ISSUE TITLE
Dragged item not attached to mouse pointer

### ISSUE THREAD

**Issue by kevinpolar** [angular-ui-tree/angular-ui-tree#645]
I just updated to the latest version (v2.10) and now, when I drag an item, the item is placed way lower than the pointer.

**Comment by Voles** [comment]
From which version have you upgraded? Can you add a screenshot / jsFiddle showing the issue?

**Comment by kevinpolar** [comment]
This is what the page originally looks like:
![image](https://cloud.githubusercontent.com/assets/15812290/11174492/6e43aa4e-8c5f-11e5-9bcc-676db06c593c.png)

the next image is right after when I click on an item to try and drag it:
![image](https://cloud.githubusercontent.com/assets/15812290/11174516/b3df772c-8c5f-11e5-9d6f-b2706343269f.png)

My mouse pointer is located where the red box is in the photo(print screen won't include the pointer) and the item being dragged is placed way below the pointer near the blue button.

Initially, the version that was being used was v2.2, I updated it to v2.10 then this happened, I did try an experiment, I updated from v2.2 up until v2.10 going each iteration. v2.3 till v2.9 looked ok and behaved the same in terms of dragging the item, the jump from v2.9 to v2.10 then gave me the result shown in the second image.

Hope this helps

**Comment by StefanCodes** [comment]
@kevinpolar are you seeing this behaviour in the demos (http://angular-ui-tree.github.io/angular-ui-tree/#/basic-example) as well? If yes, what browser/OS? If no, can you post a plunk with a part of your app to demonstrate? I can't reproduce this in the demos or my web app that uses ui-tree.

**Comment by qcmatsuoka** [comment]
@kevinpolar +1

Hi.
I had same problem.

I think the cause of this problem is the location where declare `ng-app`.
Relative position will shift when the block elements are inserted the left or top.

Here is my sample.
http://plnkr.co/edit/RROl0V6tIoOyD0pZ1RhL?p=preview

It is possible to correspond with one of the following.

1. change `$rootElement` to `"body"`
    * https://github.com/angular-ui-tree/angular-ui-tree/blob/master/dist/angular-ui-tree.js#L695
1. change manual startup angular
    * http://plnkr.co/edit/lwCcdAi9O3SYpU9WI2L0?p=preview
    
I propose the following things.
How about this?

```
// Get root element from scope variable.
.directive('uiTreeNode', [...
  function (...) {
    return {
        scope: {
            rootElement: '='
        },
        link: function () {
            ...
            (scope.rootElement || $rootElement).append(dragElm);
        }
```

**Comment by qckanemoto** [comment]
@qcmatsuoka +1

**Comment by pelizza** [comment]
+1
I'm experiencing the same issue here. @qcmatsuoka's solution works well.

**Comment by pelizza** [comment]
Also, I confirm that the problem started between versions v2.9 to v2.10.

**Comment by jozsinakhivnak** [comment]
I can confirm that @qcmatsuoka's solution works well. Just change the line 
`  $rootElement.append(dragElm);`
to

`  $document.find('body').append(dragElm);`

**Comment by Smolations** [comment]
+1

This is happening in v2.15.0 as well. I have changed my manual bootstrapping to target the `body` instead of `document`, but another solution may be needed if the root element needs to be the `document` in order to dynamically change the `<title>` for various routes.

I think I may favor @jozsinakhivnak's solution in favor of the solution proposed by @qcmatsuoka because it would be tedious to modify an attribute for every `ui-tree-node` when they are nested. Is there any use case where always appending to the `body` would not be desired?

**Comment by jacobscarter** [comment]
This line change is in the latest release `$document.find('body').append(dragElm)`
