### ISSUE TITLE
Demos and examples aren't working?

### ISSUE THREAD

**Issue by ittikorns** [angular-ui-tree/angular-ui-tree#680]
I was trying to figure out why drag and drop table rows doesn't work on my site. Then I come back and check the demos again and it seems like it doesn't work as well.

http://angular-ui-tree.github.io/angular-ui-tree/#/table-example

When you drop the element it just go back into the same order.

**Comment by zachlysobey** [comment]
No idea how to fix, but I think I can write a e2e test to confirm this as broken.

**Comment by StefanCodes** [comment]
Argh, that was caused by https://github.com/angular-ui-tree/angular-ui-tree/pull/589 - my bad.
The problem is that `beforeDrop` only passes (and thus processes the drop event) when the caller code implements the `beforeDrop` callback and return truthy. 
Right now if it's not implemented, ui-tree will assume the drop event was rejected and undo the drop.

I can submit a PR for this tonight. Sorry, that was sloppy.

**Comment by zachlysobey** [comment]
I tried to get an e2e test (#682) for this, but it's not working as expected...

**Comment by StefanCodes** [comment]
Submitted https://github.com/angular-ui-tree/angular-ui-tree/pull/683
