### ISSUE TITLE
Conflict with treeControl

### ISSUE THREAD

**Issue by tambovchanin** [angular-ui-tree/angular-ui-tree#795]
Hi!

Thank you for your control. 
I am find conflict when using it with another tree https://github.com/wix/angular-tree-control,
`ui.tree` lost their css styles when I am inject `treeControl`

**Comment by jacobscarter** [comment]
I don't know if this is something angular-ui-tree should address.  The class names are already pretty customized, e.g. `.angular-ui-tree-nodes` and they shouldn't be much more specific or locked down because then it will be more difficult to override the styles if the user wishes to.

**Comment by StefanCodes** [comment]
This sounds like a coincidental collision of CSS class names as user by another tree-based control.

I think the only real solution here is for one of those controls to rename the classes they use, and that's going to cause breaking changes for all the users of one of the other control. 

Furthermore, I'm not sure this is a problem anymore, either. I see on their readme (https://github.com/wix/angular-tree-control#styling) that they're using classes named tree-classic, tree-expanded, etc. We're using ui-tree-xx.

Perhaps angular-tree-control fixed this issue on their end since this was opened. If there is still an issue, I don't want to modify ui-tree to try to handle it - it will cause too many breaking changes to existing ui-tree users' templates.
