### ISSUE TITLE
Repository Cleanup

### ISSUE THREAD

**Issue by jacobscarter** [angular-ui-tree/angular-ui-tree#815]
@Voles and @StefanCodes I would like to attempt to clean up the repo a little!

Can we delete all the branches (except master and gh-pages of course)? They all reference PRs that were merged or closed.

Can I get you guys to commit to get on a timeline for closing these 259 issues also? I think most of them will be easy to close because they will be years old, reference outdates problems, etc.

Let me know what you guys think.

**Comment by Voles** [comment]
@jacobscarter I've removed the stale branches. We only have a `master` and `gh-pages` branch now.

In order to process the outstanding issues / PR's, we need some sort of process. The same idea as what we did with the CONTRIBUTING.md file.

What I suggest:
1. We add an issue template (see #816)
2. We close issues:
- older then 6 months and comment that the original author should recreate the issue if it is still relevant
- without enough information to investigate
- of which the content is outdated
- containing support questions, we should comment here with a link to our Gitter channel

**Comment by jacobscarter** [comment]
@voles Sounds good to me!

**Comment by jacobscarter** [comment]
Closing this, we are all caught up on closing issues that meet your criteria above.  From 300 to 60 :/  hopefully we can get all these PRs and Issues handled over the next couple of months!
